WHATSAPP_MESSAGES = {
  "welcome": "Olá! Eu sou um robô 🤖 e consigo enviar figurinhas aqui do Whatsapp para o Telegram. Vou te ajudar a fazer isso agora.\n\nPara começar e criar um novo pacote, me envie ```/start```",
  "start": "Uhul, um novo pacote! Como vamos chamá-lo??",
  "package_name": "Humanos têm usernames, pacotes têm packnames. Vamos criar um para o seu. Ele pode conter apenas letras (sem acentos ou espaços), \"_\" e números, e precisa começar com uma letra.\n\nEsse packname vai ser útil porque seu pacote incrível de figurinhas poderá ser adicionado pelos seus amigos usando um link como: t.me/addstickers/seu_id_aqui.",
  "package_name_error": "Oops, esse packname não é válido. Por favor, me envie um identificador válido. Ele pode conter apenas letras (sem acentos), underscore (\"_\") não consecutivo e números, e precisa começar com uma letra.\n\nSeu pacote de stickers será adicionado usando um link como: t.me/addstickers/seu_id_aqui.",
  "send_me_stickers": "Ok, vamos à parte divertida.\n\nMe envie todas as figurinhas (no mínimo 3, no máximo 120) que você quer adicionar ao pacote. \n\nEu vou ficar esperando. Quando terminar, me avise enviando um ```/done```.",
  "whats_your_telegram": "Legal! Vamos criar um pacote seu. Pra criar seu pacote, você precisa encontrar meu irmão no Telegram. O nome dele é @WhatsGramStickerBot (http://t.me/WhatsGramStickersBot).\n\nQuando encontrá-lo, clique em Começar. Ele vai te dizer pra enviar uma mensagem no WhatsApp, mas você já fez isso. \n\nSó copie o código na mensagem a seguir e envie para ele.\n\nQuando você fizer isso, ele vai me informar e eu já vou criar seu pacote e te enviar o link por aqui, ok?",
  "done": "Yupi! Seu pacote de figurinhas está saindo do forno!!! Acesse http://t.me/addstickers/{} para encontrá-lo!\n\nSe quiser gerenciá-lo, você pode encontrar o bot @Stickers no Telegram. Ele pode te ajudar a ver e editar seus pacotes!\n\nSe quiser criar mais pacotes, já sabe: envia um ```/start```",
  "unknown_error": "Ops... Encontrei um erro que não consigo resolver sozinho. Como as coisas na computação nem sempre seguem a lógica, tente enviar um ```/start``` novamente dentro de alguns minutos. Se isso não funcionar, entre em contato com meu pai humano no Telegram @helitonmrf (https://t.me/helitonmrf). ",
  "invalid_package_title": "Opa, esse nome para o pacote não é válido. Use no máximo 40 caracteres.",
  "wait_a_little_more": "Estamos criando seu pacote de Stickers. Assim que ele estiver pronto, vou te enviar o link por aqui. Pode aguardar mais um pouquinho?",
}

TELEGRAM_MESSAGES = {
    "start": "Olá! Eu sou um robô 🤖e consigo migrar suas figurinhas do WhatsApp direto aqui para o Telegram.\n\nPra isso, você vai precisar enviar uma mensagem para meu irmão no Whatsapp (como eu moro no Telegram, ele vai me ajudar me enviando suas figurinhas). Para falar com ele, envie uma mensagem para <a href='https://wa.me/5531971352054'>+55 31 971352054</a>.\n\nSe você já conversou com meu irmão, ele deve ter te enviado um código parecido com <code>999999999999@x.xx</code>. Você só precisa me enviá-lo.",
    "help": "Meu irmão e eu somos robôs e, juntos, convertemos suas figurinhas do Whatsapp para o Telegram.\n\n<b>COMO FUNCIONAMOS?</b>\nNós trabalhamos juntos. Você precisa enviar uma mensagem para o meu irmão no Whatsapp (use /start para receber o link), e ele vai te guiar nos próximos passos.\n\nOs pacotes que criamos serão feitos como sendo de sua autoria, então você poderá editá-los mais tarde.\n\n<b>COMO EDITO MEUS PACOTES?</b>\nVocê pode usar nosso amigo bot @Stickers para gerenciar todos os seus pacotes de figurinhas, mas nosso pai prometeu que vai nos ensinar a fazer isso também em breve...\n\n<b>DE QUE SOMOS FEITOS?</b>\nQuando nasci, meu pai humano me ensinou que nós somos feitos com algo chamado Python. Nós vivemos no <a href='https://github.com/hellmrf/WhatsGram-Stickers'>Github</a> e somos de código aberto.\n\nIsso é tudo o que eu sei. Se você tiver mais dúvidas, contate meu pai humano em @helitonmrf.\n\n\n<b>COMANDOS:</b>\n• /start: começar a crianção do seu pacote\n• /help: exibe esta mensagem",
    "creating": "Uhul! Meu irmão e eu já estamos criando seu pacote de figurinhas incrível. Você vai receber pelo Whatsapp, nos próximos minutos, um link para acessá-lo (e compartilhar com os amigos).",
}

TELEGRAM_MESSAGES_en = {
    "start": "Hi! To migrate your Whatsapp Stickers to Telegram, you'll need first message me in Whatsapp. Please, send me a message to https://wa.me/5531971352054.\n\nIf you already have your code, please send-me.",
    "help": "Hi! To migrate your Whatsapp Stickers to Telegram, you'll need first message me in Whatsapp. Please, send me a message to https://wa.me/5531971352054 so I can guide you through next steps. At the end, I'll send you (until via Whatsapp) a code that you will send me here.\n\nIf you already have your code, please send-me.\n\nIf you have other questions, contact my human father at @helitonmrf.",
    "creating": "Great! Wait a little more, please. I'm creating your fancy sticker set!",
}
