STAGES = {
    'UNKNOWN': 0,
    'WAITING_PACKAGE_TITLE': 1,
    'REMOVED_WAITING_PACKAGE_NAME': 2,
    'WAITING_STICKERS': 3,
    'WAITING_EMOJIS': 4,
    'WAITING_FOR_TELEGRAM': 5,
    'GENERATE_STICKERS': 6,
}